### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by Dayire** [SenticNet/conv-emotion#10]
Hey!

I would like first to thank you for everything you've done and making your codes available!

I would like to ask, to the extent possible, the pre-trained weights for DialogueRNN (baselines as well?) (for IEMOCAP and the rest of the datasets?) as I need to try your software on my datasets without retraining (due to lake of time/resource to train). I'm sure this will also benefit others as well!

Thanks :D

**Comment by soujanyaporia** [comment]
Okay. We will try to release the pre-trained weights asap. Thanks!
