### ISSUE TITLE
DialogRNN perfoms not so well on Dailydialog dataset.

### ISSUE THREAD

**Issue by lsy641** [SenticNet/conv-emotion#11]
**Describe the bug**
I wonder if there is any problem, because I can't get a good result on Dailydialog dataset.
When model converged, nearly all data are predicted as "no-emotion" or "happiness".
Data inbalance existing in Dailydialg dataset might be the reason of this problem.
But I still want to ask，anybody get the same result as me?

**To Reproduce**
run train_dailtdialog.py -lr 0.001 -epoch 50

**Screenshots**
label 4 is "happiness", and i do not print the label 2 which is "no-emotion".
so you can see all data are predicted as "happiness" or "no - emotion".

epoch 9 train_loss 0.4284 train_acc 86.24 train_fscore 49.14 valid_loss 0.3363 valid_acc 88.95 valid_fscore 50.11 test_loss 0.4913 test_acc 83.59 test_fscore 47.94 time 231.11s

             precision    recall  f1-score   support

          0     0.0000    0.0000    0.0000      17.0
          1     0.0000    0.0000    0.0000     118.0
          3     0.0000    0.0000    0.0000      47.0
          4     0.5609    0.5829    0.5717    1019.0
          5     0.0000    0.0000    0.0000     102.0
          6     0.0000    0.0000    0.0000     116.0

avg / total     0.4028    0.4186    0.4105    1419.0

**Comment by soujanyaporia** [comment]
It is because dailydialogue is an imbalanced dataset. You may use class weights for it. Hope it helps.
