### ISSUE TITLE
why does CMN show different results on IEMOCAP ?

### ISSUE THREAD

**Issue by lsy641** [SenticNet/conv-emotion#13]
**Describe the bug**
when I see papser of CMN. It did experiments on IEMOCAP, and the results are showed as below:
![image](https://user-images.githubusercontent.com/26696711/67104448-8dd1d300-f1f9-11e9-9326-f5e03e99ad6e.png)
and in your paper, you reported that CMN's weighted accuracy on IEMOCAP is much lower than above. As is showed below:
![image](https://user-images.githubusercontent.com/26696711/67104618-d7222280-f1f9-11e9-8c50-517f7315627b.png)

**Comment by soujanyaporia** [comment]
Because the number of classes is different in these two tables. Have a closer look, please.
