### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './glove.840B.300d.txt'

### ISSUE THREAD

**Issue by jaymaski** [SenticNet/conv-emotion#2]
Using TensorFlow backend.
Processing training data...
Processing test data...
Extracting tokens...
Found 15 unique tokens.
Populating embedding matrix...
Traceback (most recent call last):
  File "baseline.py", line 378, in <module>
    main()
  File "baseline.py", line 308, in main
    embeddingMatrix = getEmbeddingMatrix(wordIndex)
  File "baseline.py", line 195, in getEmbeddingMatrix
    with io.open(os.path.join(gloveDir, 'glove.840B.300d.txt'), encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: './glove.840B.300d.txt'

**Comment by soujanyaporia** [comment]
Could you please download the Glove embedding to ./ ? Thanks!

**Comment by iclr-retrospection** [comment]
Hi, can you please share a link to the file for the glove embeddings? I am unable to find it in this repository.

Thanks

**Comment by ayushchopra96** [comment]
Hi. Can you please share the train.txt used for training the bc-LSTM model.
