### ISSUE TITLE
Embedding of same sentence provided by CMN and DialogueRNN is different

### ISSUE THREAD

**Issue by lsy641** [SenticNet/conv-emotion#20]
**Is your feature request related to a problem? Please describe.**
Since you use different pkl files to provide V/U/A embeddings, I just print the text embeddings of Ses01F_impro01_F001 in "IEMOCAP_features_raw.pkl" provided in DialogueRNN project and "IEMOCAP_text_embeddings.pickle" provided in CMN project, and I found them different, as below:
![image](https://user-images.githubusercontent.com/26696711/68201094-11623100-fffc-11e9-96a4-defafdccdfbf.png)

**Describe the solution you'd like**
I wonder how you did comparison with CMN in DialogueRNN paper . Did experiments begin with same features?If not , how to ensure fairness？

**Comment by soujanyaporia** [comment]
The easiest solution is to just run CMN on these features. And yes, we did that already and reported that in the DialogueRNN paper. If you **read** the DialogueRNN paper carefully, you will see that the reported results of CMN are different from what you can find in the **original** CMN paper. Note that, the original CMN paper reports results for 4-class whereas DialogueRNN paper presents results for 7-way classification. Hope this explains everything. If yes, I would prefer to close this issue.

**Comment by lsy641** [comment]
> The easiest solution is to just run CMN on these features. And yes, we did that already and reported that in the DialogueRNN paper. If you **read** the DialogueRNN paper carefully, you will see that the reported results of CMN are different from what you can find in the **original** CMN paper. Note that, the original CMN paper reports results for 4-class whereas DialogueRNN paper presents results for 7-way classification. Hope this explains everything. If yes, I would prefer to close this issue.

I of course did run your code, ^_^. First, the code of CMN you provided is 7-class, and use "IEMOCAP_text_embeddings.pickle" , that is why I think it is exact your baseline of DialogueRNN instead of original CMN.
So, if yes, why you used different features?
If not, is it necessary change features just because CMN was changed from 4-class to 7-class? I really don't know the point.

**Comment by soujanyaporia** [comment]
The features are pre-trained features on the same dataset. Hence, features will change if you change the number of classes. Also, feature values depend on which layer you choose to extract features from the pre-trained network. Hope this clarifies all your doubts.

**Comment by lsy641** [comment]
> The features are pre-trained features on the same dataset. Hence, features will change if you change the number of classes. Also, feature values depend on which layer you choose to extract features from the pre-trained network. Hope this clarifies all your doubts.

So, in your 4-class pre-train proccess, how did you treat the data whose labels are the other 3 class? just neglect them?

**Comment by soujanyaporia** [comment]
Yes and Yes. 
<img width="317" alt="Screenshot 2019-11-07 at 1 11 03 PM" src="https://user-images.githubusercontent.com/40890991/68361782-15a75f00-0160-11ea-967b-b31798995912.png">

**Comment by lsy641** [comment]
Thanks, I understand it.
