### ISSUE TITLE
Data Preprocessing Code of DialogueGCN

### ISSUE THREAD

**Issue by luhengtong** [SenticNet/conv-emotion#25]
Thank you for releasing the DialogueGCN code. Can you post the data preprocessing code of DialogueGCN or tell me where I can find it. I don't understand the data in file IEMOCAP_features.pkl.
Thanks.

**Comment by qniguoym** [comment]
If I use features that DialogueRNN used, the model is easy to be overfitted. So can you tell us how to extract the features better? Thanks.

**Comment by 201520815029009** [comment]
I am also confused about the data in IEMOCAP_features.pkl. The sentence in dialog in 'videoText' is a vector with 100 dimensions. Is this the output of CNN embedding?

**Comment by soujanyaporia** [comment]
The model will overfit if you set lr to 0.001. 
Yes, this is the output of CNN embedding.

**Comment by qniguoym** [comment]
> The model will overfit if you set lr to 0.001.
> Yes, this is the output of CNN embedding.

We set lr to 0.001, it also be overfitted.  The model is sensitive to the features. Can you share the  code for feature extraction ?   I want to know when to stop the training in the feature extraction stage. The feature file for DialogueRNN is different from the file for DialogGCN. Thanks.

**Comment by soujanyaporia** [comment]
The DialogueGCN and DialogueRNN features should be the same. The way we format the data in the pkl is a bit different.

**Comment by qniguoym** [comment]
> The DialogueGCN and DialogueRNN features should be the same. The way we format the data in the pkl is a bit different.

Yes, maybe something is wrong in my experiment. Thank you very much!

**Comment by soujanyaporia** [comment]
Closing the issue.
