### ISSUE TITLE
Train DialogueGCN on MELD

### ISSUE THREAD

**Issue by snailcoder** [SenticNet/conv-emotion#26]
I'm a little confused about how many emotion classes are used for classification when conducting experiments on MELD dataset described in this paper: **DialogueGCN: A Graph Convolutional Neural Network for Emotion Recognition in Conversation**.

I can only reproduce results of **CNN** and **CNN+cLSTM** when I set the number of emotion classes of MELD to three, instead of seven.

Could you release the code for training DialogueGCN on MELD just like train_MELD.py in the directory of DialogueRNN?

**Comment by soujanyaporia** [comment]
You will need to use a set of class weights. We plan to release it soon. The hyperparams are also different for MELD.
