### ISSUE TITLE
label index  mapping of DailyDialogue

### ISSUE THREAD

**Issue by shanpku** [SenticNet/conv-emotion#41]
Hi! I'm trying to run train_dailydialog.py,  but I don't understand what's the meaning of labels index.
`avg_fscore = round(f1_score(labels,preds,sample_weight=masks,average='micro', labels=[0,2,3,4,5,6])*100,2)`
i couldn't find any comment about the label index mapping.,but  i think dailydialogue have 7 label, why here are only 6 ? 
Thanks for help!

**Comment by RaleLee** [comment]
Maybe I can explain this. Dailydialog dataset is an unbalance dataset. The 'no_emotion' label is about 83% in the whole emotion label. You can run preprocess_dailydialog.py to check the all encoded emotion label. Notice that the preprocess emotional dict will change in different run! 
In preprocess_dailydialog.py line 78, add some print method:


        for i, label in enumerate(all_emotion_labels):
            emotion_label_encoder[label] = i
            print(str(i) + " " + str(label))
            emotion_label_decoder[i] = label
            print(str(emotion_label_encoder[label]) + " " + str(emotion_label_decoder[i]))

So the answer is, in preprocessing time, the 'no_emotion' label matched to encoded label 1. When it comes to calculate f1 score, writer try to mask this label to get a more specific result.

**Comment by shanpku** [comment]
Thank you, I understand it!
