### ISSUE TITLE
Tuning params on test dataset

### ISSUE THREAD

**Issue by haoqi** [SenticNet/conv-emotion#6]
From your training scripts, all *best_loss*, *best_pred* etc. are obtained from tuning on test dataset, the dev_set is not used to selected the correct model.
This might be a critical issue in the paper to claim your results are better than the STOA.

**Comment by soujanyaporia** [comment]
We have not included the hyper parameter selection process in the training code. This can be easily done by splitting the training data in any of the training scripts. The present code simply prints test result on every epoch.

**Comment by haoqi** [comment]
You are right. I see your points. In your code, you already split the dev set from training and print dev result on every epoch. (Different from what you said: "The present code simply prints test result on every epoch."). However, you select best_loss on test dataset on each epoch during training. You can print the test results on every epoch, but from your code, it seems that you tried to use the dev set, but you did not use it in the correct way.

**Comment by devamanyu** [comment]
Hi @haoqi ,

You are right in pointing out that this might confuse users that test_loss is being used for model selection. Thanks for the pointer, we shall clarify it in our code!  

If you have any more doubts, let's connect through email: soujanya.poria@gmail.com, hazarika@comp.nus.edu.sg
