### ISSUE TITLE
Two Questions Regarding CMN model source code

### ISSUE THREAD

**Issue by PeterPanUnderhill** [SenticNet/conv-emotion#7]
Have read the paper and the source code, found two curious points.

1. In the paper, the memory representation directly uses (equals to) the GRU's internal states. But in the code, it seems the memory representation goes through another GRU cell. 
As you can see below, the "ownHistoryRNNOutput" are already the hidden states from the GRU cell, they are however further fed into the "self.memoryGRUown", which doesn't accord with the descriptions in the paper.

`input_rnn_outputs_own, final_state = tf.nn.dynamic_rnn(self.memoryGRUown, ownHistoryRNNOutput, dtype=tf.float32)`
`output_rnn_outputs_own, final_state = tf.nn.dynamic_rnn(self.memoryGRUown, ownHistoryRNNOutput, dtype=tf.float32)`

So which one is correct?

2. In the same part of the code which we can see above, it seems the "input_rnn_outputs_own" and "output_rnn_outputs_own" share the same GRUCell (I didn't find any scope definition),  therefore should have the same values. This also doens't accord with the descriptions in the paper, which uses two different GRU cells, M and M'. 

Could anyone explain them to me? Or I misunderstood somewhere?

**Comment by devamanyu** [comment]
Hi @PeterPanUnderhill ,

First of all, thank you for your interest in our work in conv-emotion. 

Let me clarify that the results in our CMN paper are based on the exact architecture written in the paper. 

The repository here is a reimplementation based on our format of the ICON model, which induced some changes, such as the ones you mentioned above. The extra GRU in the memory representation is influenced by the DGIM module in ICON. We also experimented with reducing parameters by tying the weights of the input and output GRUs. These changes didn't provide significant differences in our original CMN results. However, we encourage you to try the other versions as well. Hope this helps!

**Comment by PeterPanUnderhill** [comment]
> u

Hi @devamanyu , thanks for you quick and detailed reply. 

Now I understand this is not the exact implementation of CMN, and it explains the difference between the paper and the source code. I thought I was missing something either in the paper or in the code, it's good to know that I didn't misunderstand. Since there's no significant difference in the results of the two models, I will first try with this version :)

By the way, cool work with emotion recognition from conversations. I have read many papers from your group and will keep following your progress.

Thanks again for the explanation!

**Comment by soujanyaporia** [comment]
Thanks @PeterPanUnderhill. As you are interested in this topic, please take a look at this paper - https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8764449
