### ISSUE TITLE
About the bidirectional RNN representing conversation flow

### ISSUE THREAD

**Issue by lrh000** [SenticNet/conv-emotion#8]
Hi,

I recently read your DialogueGCN, and I have a question about the conversation flow. Since conversations are sequential by nature, why use bidirectional RNN to capture the contextual information?

Moreover, in this paper, both the graph construction and Equation (5) mean the each utterance need consider each other utterance including these from the future window. Of course, you have given the explanation that "While past utterances influencing future utterances is natural, the
converse may help the model fill in some relevant missing information, that is part of the speaker’s background knowledge but explicitly appears in the conversation in the future." However, in real-life dialogue, the emotion of the interlocutor should only be influenced by the history of the dialogue, because it is impossible to predict the future content of the dialogue.

Do you think this is reasonable? Appreciate for any suggestion.

**Comment by soujanyaporia** [comment]
If your system is not real time and you plan to utilise whole context in your task, they yes, you may use the future utterances.

**Comment by lrh000** [comment]
> If your system is not real time and you plan to utilise whole context in your task, they yes, you may use the future utterances.

Thanks for reply. I also read your DialogueRNN and CMN, and the former shows the effect of the undirectional RNN. This approach is outstanding as long as the definition of the ERC task is limited to global prediction.

**Comment by soujanyaporia** [comment]
Thanks very much! Have a look at this paper too - https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8764449&tag=1
