### ISSUE TITLE
where is DialogueGCN code?

### ISSUE THREAD

**Issue by dedoogong** [SenticNet/conv-emotion#9]
Could you please let me know where I can find the implementation for  DialogueGCN?

Thank you!

**Comment by soujanyaporia** [comment]
Hi,

Thanks for asking. We are making some changes in order to enhance the readability plus we are adding more functionalities to it. It will be available soon.

**Comment by deepanwayx** [comment]
Hi @dedoogong,  The code for DialogueGCN has been released.
